# .github/workflows/doxygen.yml
name: Generate Doxygen Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz

    - name: Create Doxyfiles
      run: |
        # Labos 1 Doxyfile
        cat > Lab1/Doxyfile << 'EOL'
        PROJECT_NAME           = "Arduino IRS"
        PROJECT_NUMBER         = "1.0"
        PROJECT_BRIEF          = "Sustav s Prekidima za Arduino"
        OUTPUT_DIRECTORY       = ../docs/lab1
        INPUT                  = .
        FILE_PATTERNS          = *.ino *.h *.cpp
        RECURSIVE              = YES
        GENERATE_HTML          = YES
        GENERATE_LATEX         = NO
        HTML_OUTPUT            = html
        HAVE_DOT               = YES
        UML_LOOK               = YES
        EXTRACT_ALL            = YES
        EOL
        
        # Labos 2 Doxyfile
        cat > Lab2/Doxyfile << 'EOL'
        PROJECT_NAME           = "Arduino Sleep Mode"
        PROJECT_NUMBER         = "1.0"
        PROJECT_BRIEF          = " Program za upravljanje potrošnjom energije Arduino mikrokontrolera korištenjem sleep modova"
        OUTPUT_DIRECTORY       = ../docs/lab2
        INPUT                  = .
        FILE_PATTERNS          = *.ino *.h *.cpp
        RECURSIVE              = YES
        GENERATE_HTML          = YES
        GENERATE_LATEX         = NO
        HTML_OUTPUT            = html
        HAVE_DOT               = YES
        UML_LOOK               = YES
        EXTRACT_ALL            = YES
        EOL
        
        # Projekt Doxyfile
        cat > Projekt/Doxyfile << 'EOL'
        PROJECT_NAME           = "Monitor za Bebe"
        PROJECT_NUMBER         = "1.0"
        PROJECT_BRIEF          = "Projekt za Ugradbene sustave"
        OUTPUT_DIRECTORY       = ../docs/Projekt
        INPUT                  = .
        FILE_PATTERNS          = *.ino *.h *.cpp
        RECURSIVE              = YES
        GENERATE_HTML          = YES
        GENERATE_LATEX         = NO
        HTML_OUTPUT            = html
        HAVE_DOT               = YES
        UML_LOOK               = YES
        EXTRACT_ALL            = YES
        EOL
        
        # Index datoteka za navigaciju između projekata
        mkdir -p docs
        cat > docs/index.html << 'EOL'
        <!DOCTYPE html>
        <html>
        <head>
          <title>Arduino Projekti Dokumentacija</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            h1 { color: #333; }
            .project-list { list-style-type: none; padding: 0; }
            .project-list li { margin-bottom: 15px; }
            .project-list a { color: #0066cc; text-decoration: none; font-weight: bold; }
            .project-list a:hover { text-decoration: underline; }
            .description { color: #666; }
          </style>
        </head>
        <body>
          <h1>Arduino Projekti Dokumentacija</h1>
          <p>Dobrodošli u dokumentaciju za kolekciju Arduino projekata.</p>
          
          <h2>Dostupni projekti:</h2>
          <ul class="project-list">
            <li>
              <a href="./Lab2/html/index.html">Arduino Sleep Mode</a>
              <div class="description">Program za upravljanje potrošnjom energije Arduino mikrokontrolera korištenjem sleep modova</div>
            </li>
            <li>
              <a href=".Projekt/html/index.html">Monitor Za Bebe</a>
              <div class="description">Projekt Ugradbenih Sustsava</div>
            </li>
          </ul>
        </body>
        </html>
        EOL

    - name: Generate Documentation
      run: |
        # Generiranje dokumentacije za svaki projekt
        cd Lab1 && doxygen Doxyfile && cd ..
        cd Lab2 && doxygen Doxyfile && cd ..
        cd Projekt doxygen Doxyfile && cd ..

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs