# .github/workflows/doxygen.yml
name: Generate Doxygen Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz

    - name: Create Doxyfiles
      run: |
        # Labos 1 Doxyfile
        cat > Lab1/Doxyfile << 'EOL'
        PROJECT_NAME           = "Arduino IRS"
        PROJECT_NUMBER         = "1.0"
        PROJECT_BRIEF          = "Sustav s Prekidima za Arduino"
        OUTPUT_DIRECTORY       = ../docs/lab1
        INPUT                  = .
        FILE_PATTERNS          = *.ino *.h *.cpp
        RECURSIVE              = YES
        GENERATE_HTML          = YES
        GENERATE_LATEX         = NO
        HTML_OUTPUT            = html
        HAVE_DOT               = YES
        UML_LOOK               = YES
        EXTRACT_ALL            = YES
        EXTENSION_MAPPING      = ino=C++
        SOURCE_BROWSER         = YES
        INLINE_SOURCES         = YES
        EOL
        
        # Labos 2 Doxyfile
        cat > Lab2/Doxyfile << 'EOL'
        PROJECT_NAME           = "Arduino Sleep Mode"
        PROJECT_NUMBER         = "1.0"
        PROJECT_BRIEF          = " Program za upravljanje potrošnjom energije Arduino mikrokontrolera korištenjem sleep modova"
        OUTPUT_DIRECTORY       = ../docs/lab2
        INPUT                  = .
        FILE_PATTERNS          = *.ino *.h *.cpp
        RECURSIVE              = YES
        GENERATE_HTML          = YES
        GENERATE_LATEX         = NO
        HTML_OUTPUT            = html
        HAVE_DOT               = YES
        UML_LOOK               = YES
        EXTRACT_ALL            = YES
        EXTENSION_MAPPING      = ino=C++
        SOURCE_BROWSER         = YES
        INLINE_SOURCES         = YES
        EOL
        
        # Projekt Doxyfile
        cat > Projekt/Doxyfile << 'EOL'
        PROJECT_NAME           = "Monitor za Bebe"
        PROJECT_NUMBER         = "1.0"
        PROJECT_BRIEF          = "Projekt za Ugradbene sustave"
        OUTPUT_DIRECTORY       = ../docs/Projekt
        INPUT                  = .
        FILE_PATTERNS          = *.ino *.h *.cpp
        RECURSIVE              = YES
        GENERATE_HTML          = YES
        GENERATE_LATEX         = NO
        HTML_OUTPUT            = html
        HAVE_DOT               = YES
        UML_LOOK               = YES
        EXTRACT_ALL            = YES
        EXTENSION_MAPPING      = ino=C++
        SOURCE_BROWSER         = YES
        INLINE_SOURCES         = YES
        EOL
        
        # Index datoteka za navigaciju između projekata
        mkdir -p docs
        cat > docs/index.html << 'EOL'
        <!DOCTYPE html>
          <title>Arduino Projekti Dokumentacija</title>
          <style>
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              background-color: #f9f9f9;
              color: #2c3e50;
              margin: 40px auto;
              max-width: 800px;
              line-height: 1.8;
              padding: 0 20px;
            }
        
            h1, h2 {
              color: #2c3e50;
            }
        
            h1 {
              font-size: 2.5em;
              margin-bottom: 10px;
            }
        
            h2 {
              font-size: 1.6em;
              margin-top: 40px;
              margin-bottom: 20px;
              border-bottom: 2px solid #e0e0e0;
              padding-bottom: 5px;
            }
        
            .project-list {
              list-style: none;
              padding: 0;
              margin: 0;
            }
        
            .project-list li {
              background: #ffffff;
              border: 1px solid #e0e0e0;
              border-radius: 12px;
              padding: 20px;
              margin-bottom: 15px;
              box-shadow: 0 2px 5px rgba(0, 0, 0, 0.03);
              transition: transform 0.2s ease, box-shadow 0.2s ease;
            }
        
            .project-list li:hover {
              transform: translateY(-2px);
              box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
            }
        
            .project-list a {
              color: #2980b9;
              text-decoration: none;
              font-size: 1.2em;
              font-weight: 600;
              display: inline-block;
              margin-bottom: 8px;
            }
        
            .project-list a:hover {
              text-decoration: underline;
            }
        
            .description {
              color: #7f8c8d;
              font-size: 0.95em;
            }
        
            p {
              color: #555;
              font-size: 1.05em;
            }
          </style>
        </head>
        <body>
          <h1>Arduino Projekti Dokumentacija</h1>
          <p>Dobrodošli u dokumentaciju za kolekciju Arduino projekata.</p>
          
          <h2>Dostupni projekti:</h2>
          <ul class="project-list">
            <li>
              <a href="./lab1/html/index.html">Arduino ISR</a>
              <div class="description">Sustav s Prekidima za Arduino</div>
            </li>
            <li>
              <a href="./lab2/html/index.html">Arduino Sleep Mode</a>
              <div class="description">Program za upravljanje potrošnjom energije Arduino mikrokontrolera korištenjem sleep modova</div>
            </li>
            <li>
              <a href="./Projekt/html/index.html">Monitor Za Bebe</a>
              <div class="description">Projekt Ugradbenih Sustava</div>
            </li>
          </ul>
        </body>
        </html>
        EOL

    - name: Generate Documentation
      run: |
        # Generiranje dokumentacije za svaki projekt
        cd Lab1 && doxygen Doxyfile && cd ..
        cd Lab2 && doxygen Doxyfile && cd ..
        cd Projekt && doxygen Doxyfile && cd ..

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
